vlm_prompts:
  description_image: """
# 图像内容描述提示

## 任务
使用视觉语言模型生成图像内容的详细描述。

## 背景
- 视觉语言模型可以处理图像并生成文本描述
- 需要结构化输出以实现一致的图像分析
- 关注关键视觉元素及其关系

## 输入
- 图像格式：JPG、PNG或类似的视觉格式
- 图像内容：任何视觉场景、物体或构图

## 输出
请描述图像的以下方面：
1. 场景中的主要主体/物体
2. 元素之间的空间关系
3. 颜色和视觉特征
4. 动作或活动（如果有）
5. 环境背景
6. 任何文本或符号
7. 整体场景构图

示例模板：
“这张图片显示了[主要主体]在[位置]。[物体]是[空间关系]。主要颜色是[颜色]。[关于动作/背景的其他详细信息]。”

    """
  ocr_image: """
# OCR 图像到 Markdown 转换提示

## 任务
将图像内容转换为 markdown 格式，特别处理文本、公式和结构化内容。

## 背景
- 图像可能包含混合内容，包括文本、数学公式、表格和图表
- 需要准确的 OCR 文本提取和公式识别
- 输出应为格式良好的 markdown，便于集成

## 输入
- 任何包含文本、公式、图表或混合内容的图像
- 常见格式：PNG、JPG、TIFF
- 各种类型：文档扫描、截图、书写内容的照片

## 输出
- 保留原始结构的干净 markdown 文本
- 数学公式用 $$ 分隔符括起来
- 示例：
    ```markdown
    # 检测到的标题

    常规文本内容...

    $$E = mc^2$$

    更多文本和内容...
    ```

"""