prompts:
  coolpapaers:
    description: "复刻 papers.cool"
    template: |
      请分析以下论文内容，回答如下问题：

      Q: 这篇论文是什么？
      概括该论文是做什么的。

      Q: 这篇论文试图解决什么问题？
      请详细说明论文要解决的主要问题和研究动机。

      Q: 有哪些相关研究？
      请列举与本文相关的主要研究工作和研究方向。

      Q: 论文如何解决这个问题？
      请详细说明论文提出的解决方案、方法和技术细节。

      Q: 论文做了哪些实验？
      请说明论文中的实验设计、数据集、评估指标和主要结果。

      Q: 有什么可以进一步探索的点？
      请分析论文存在的局限性以及未来可能的研究方向。

      Q: 总结一下论文的主要内容
      请对论文的问题背景、方法、实验和贡献进行总体概括。

      {text}
  yuanbao:
    description: "类似混元元宝总结"
    template: |
      请分析以下论文内容，提供一个全面的总结分析，包括：
      0. 论文大意
      1. 研究背景和动机、难点
      2. 研究方法
      3. 实验设计（如果文章提到，需要详细给出数据、样本、参数信息，不得遗漏）
      4. 结果分析

      {text}

  methodology:
    description: "研究方法论分析"
    template: |
      请详细分析以下论文的研究方法论，重点关注：
      1. 研究设计和框架
      2. 数据收集和处理方法
      3. 实验设置和参数选择
      4. 评估指标和基准
      5. 方法的创新性和局限性

      {text}

  results:
    description: "实验结果分析"
    template: |
      请分析以下论文的实验结果，包括：
      1. 主要实验发现
      2. 定量和定性分析
      3. 与基准方法的比较
      4. 消融研究结果
      5. 结果的可靠性和普适性

      {text}

  contribution:
    description: "主要贡献分析"
    template: |
      请分析以下论文的主要学术贡献，包括：
      1. 理论创新点
      2. 技术突破
      3. 方法改进
      4. 应用价值
      5. 对领域的影响

      {text}

  full_analysis:
    description: "全面深入分析"
    template: |
      请对以下论文进行全面深入的分析，包括：
      1. 研究背景和意义
         - 研究动机
         - 问题定义
         - 现有方法的局限

      2. 技术方法
         - 理论基础
         - 方法创新
         - 实现细节
         - 技术优势

      3. 实验评估
         - 实验设置
         - 数据集
         - 评估指标
         - 对比方法
         - 实验结果

      4. 创新贡献
         - 理论贡献
         - 技术贡献
         - 应用价值

      5. 局限与展望
         - 方法局限性
         - 未来改进方向
         - 潜在研究方向

      请以结构化的方式组织分析结果，重点突出论文的创新点和实际价值。

      {text}
